apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: dophermal
  labels:
    component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      initContainers:
      - name: initialize-sqlite
        image: busybox
        command: ['sh', '-c', 'touch /dophermal.db']
      containers:
      - name: dophermal-api-image
        image: dophermal-api-image
        ports:
        - containerPort: 8000
        env:
          - name: PORT
            value: "8000"
          - name: SQLITE_DATABASE_PATH
            value: "/dophermal.db"
          - name: AWS_SECRET_NAME
            value: "prod/dophermal"
        envFrom:
          - secretRef:
              name: dophermal-aws-secrets
