kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: dophermal
  name: sqlite-pvc
  labels:
    component: sqlite-claim
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi