kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: dophermal
  name: sqlite-pvc
  labels:
    component: sqlite-claim
spec:

  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      name: sqlite-storage-class