/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthCallbackImport } from './routes/auth/callback'
import { Route as ProtectedDashboardLayoutImport } from './routes/_protected/_dashboard-layout'
import { Route as ProtectedDashboardLayoutDashboardReposImport } from './routes/_protected/_dashboard-layout/dashboard_/repos'
import { Route as ProtectedDashboardLayoutDashboardEphermalsImport } from './routes/_protected/_dashboard-layout/dashboard_/ephermals'
import { Route as ProtectedDashboardLayoutDashboardRepoOwnerRepoNameIndexImport } from './routes/_protected/_dashboard-layout/dashboard_/repo_/$owner/$repoName/index'
import { Route as ProtectedDashboardLayoutDashboardRepoOwnerRepoNamePullsPullImport } from './routes/_protected/_dashboard-layout/dashboard_/repo_/$owner/$repoName/pulls/$pull'

// Create/Update Routes

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthCallbackRoute = AuthCallbackImport.update({
  path: '/auth/callback',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedDashboardLayoutRoute = ProtectedDashboardLayoutImport.update({
  id: '/_dashboard-layout',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedDashboardLayoutDashboardReposRoute =
  ProtectedDashboardLayoutDashboardReposImport.update({
    path: '/dashboard/repos',
    getParentRoute: () => ProtectedDashboardLayoutRoute,
  } as any)

const ProtectedDashboardLayoutDashboardEphermalsRoute =
  ProtectedDashboardLayoutDashboardEphermalsImport.update({
    path: '/dashboard/ephermals',
    getParentRoute: () => ProtectedDashboardLayoutRoute,
  } as any)

const ProtectedDashboardLayoutDashboardRepoOwnerRepoNameIndexRoute =
  ProtectedDashboardLayoutDashboardRepoOwnerRepoNameIndexImport.update({
    path: '/dashboard/repo/$owner/$repoName/',
    getParentRoute: () => ProtectedDashboardLayoutRoute,
  } as any)

const ProtectedDashboardLayoutDashboardRepoOwnerRepoNamePullsPullRoute =
  ProtectedDashboardLayoutDashboardRepoOwnerRepoNamePullsPullImport.update({
    path: '/dashboard/repo/$owner/$repoName/pulls/$pull',
    getParentRoute: () => ProtectedDashboardLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/_protected/_dashboard-layout': {
      preLoaderRoute: typeof ProtectedDashboardLayoutImport
      parentRoute: typeof ProtectedImport
    }
    '/auth/callback': {
      preLoaderRoute: typeof AuthCallbackImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/_protected/_dashboard-layout/dashboard/ephermals': {
      preLoaderRoute: typeof ProtectedDashboardLayoutDashboardEphermalsImport
      parentRoute: typeof ProtectedDashboardLayoutImport
    }
    '/_protected/_dashboard-layout/dashboard/repos': {
      preLoaderRoute: typeof ProtectedDashboardLayoutDashboardReposImport
      parentRoute: typeof ProtectedDashboardLayoutImport
    }
    '/_protected/_dashboard-layout/dashboard/repo/$owner/$repoName/': {
      preLoaderRoute: typeof ProtectedDashboardLayoutDashboardRepoOwnerRepoNameIndexImport
      parentRoute: typeof ProtectedDashboardLayoutImport
    }
    '/_protected/_dashboard-layout/dashboard/repo/$owner/$repoName/pulls/$pull': {
      preLoaderRoute: typeof ProtectedDashboardLayoutDashboardRepoOwnerRepoNamePullsPullImport
      parentRoute: typeof ProtectedDashboardLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ProtectedRoute.addChildren([
    ProtectedDashboardLayoutRoute.addChildren([
      ProtectedDashboardLayoutDashboardEphermalsRoute,
      ProtectedDashboardLayoutDashboardReposRoute,
      ProtectedDashboardLayoutDashboardRepoOwnerRepoNameIndexRoute,
      ProtectedDashboardLayoutDashboardRepoOwnerRepoNamePullsPullRoute,
    ]),
  ]),
  AuthCallbackRoute,
  AuthLoginRoute,
])

/* prettier-ignore-end */
