apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ./secrets

images:
  - name: dophermal-ui-image
    newName: mayursiinh/dophermal-ui
  - name: dophermal-api-image
    newName: mayursiinh/dophermal-api
  - name: dophermal-controller-image
    newName: mayursiinh/dophermal-controller

patchesJson6902:
  # sqlite volume mount
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: api-development
    patch: ./sqlite-volume-mount.yaml
