apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ./secrets

images:
  - name: dophermal-ui-image
    # k3d-registry.localhost:555 -> check hacks/local-k3d.sh
    newName: k3d-registry.localhost:5555/dophermal-ui
  - name: dophermal-api-image
    newName: k3d-registry.localhost:5555/dophermal-api
  - name: dophermal-controller-image
    newName: k3d-registry.localhost:5555/dophermal-controller

patches:
  # sqlite volume mount
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: api-development
    path: sqlite-volume-mount.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      # name: api-development
    path: always-pull-policy.yaml
